/**
 * Spatial information on each trail location and suggested walking route.
 * Extracted from KML generated by Google MyMaps, converted to JSON via:
 *      http://mapbox.github.io/togeojson/
 * then hand-edited to strip out guff (and fix split walking-route polyline)
 */
trailGeoJson = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -2.5805962,
                    51.4493936,
                    0
                ]
            },
            "properties": {
                "name": "tm-plat3",
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -2.5825918,
                    51.4490994,
                    0
                ]
            },
            "properties": {
                "name": "tm-outdoor-beds",
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -2.5862074,
                    51.449514,
                    0
                ]
            },
            "properties": {
                "name": "temple-st-100",
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -2.5884323,
                    51.449061,
                    0
                ]
            },
            "properties": {
                "name": "chatterton-birthplace",
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -2.5899263,
                    51.4486598,
                    0
                ]
            },
            "properties": {
                "name": "mary-redcliffe",
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -2.5836271,
                    51.4487267,
                    0
                ]
            },
            "properties": {
                "name": "engine-shed",
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -2.5930631,
                    51.4495039,
                    0
                ]
            },
            "properties": {
                "name": "hole-in-the-wall",
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -2.5959492,
                    51.4504283,
                    0
                ]
            },
            "properties": {
                "name": "destination-bristol",
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -2.59988,
                    51.4506005,
                    0
                ]
            },
            "properties": {
                "name": "anchor-square",
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -2.6009005,
                    51.4498199,
                    0
                ]
            },
            "properties": {
                "name": "millenium-square",
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [
                        -2.5805962,
                        51.4493936,
                        0
                    ],
                    [
                        -2.5810361000000004,
                        51.4496544,
                        0
                    ],
                    [
                        -2.5811152,
                        51.4496193,
                        0
                    ],
                    [
                        -2.5812373,
                        51.4496878,
                        0
                    ],
                    [
                        -2.5825703,
                        51.4490768,
                        0
                    ],
                    [
                        -2.5835507,
                        51.4486447,
                        0
                    ],
                    [
                        -2.5845438,
                        51.44914870000001,
                        0
                    ],
                    [
                        -2.584767,
                        51.4493936,
                        0
                    ],
                    [
                        -2.5850071,
                        51.44940950000001,
                        0
                    ],
                    [
                        -2.5851808,
                        51.449521000000004,
                        0
                    ],
                    [
                        -2.5861846,
                        51.4497504,
                        0
                    ],
                    [
                        -2.5862194,
                        51.4492841,
                        0
                    ],
                    [
                        -2.5865922000000006,
                        51.4491855,
                        0
                    ],
                    [
                        -2.5874558,
                        51.4492224,
                        0
                    ],
                    [
                        -2.5878418,
                        51.4491558,
                        0
                    ],
                    [
                        -2.5884262,
                        51.44919310000001,
                        0
                    ],
                    [
                        -2.5885113,
                        51.4490604,
                        0
                    ],
                    [
                        -2.5886172,
                        51.4489921,
                        0
                    ],
                    [
                        -2.5888289,
                        51.4489961,
                        0
                    ],
                    [
                        -2.5890646000000004,
                        51.4489003,
                        0
                    ],
                    [
                        -2.5896809,
                        51.44899620000001,
                        0
                    ],
                    [
                        -2.5899263,
                        51.4486598,
                        0
                    ],
                    [
                        -2.5901878,
                        51.4485745,
                        0
                    ],
                    [
                        -2.5905901,
                        51.4486147,
                        0
                    ],
                    [
                        -2.591089,
                        51.4492632,
                        0
                    ],
                    [
                        -2.5925857,
                        51.4494872,
                        0
                    ],
                    [
                        -2.5927037,
                        51.4494304,
                        0
                    ],
                    [
                        -2.5930631,
                        51.4495039,
                        0
                    ],
                    [
                        -2.5937498,
                        51.4498048,
                        0
                    ],
                    [
                        -2.5946939,
                        51.4505202,
                        0
                    ],
                    [
                        -2.5964239,
                        51.4506565,
                        0
                    ],
                    [
                        -2.5963797,
                        51.4508011,
                        0
                    ],
                    [
                        -2.5973225,
                        51.4508846,
                        0
                    ],
                    [
                        -2.5975169,
                        51.4500138,
                        0
                    ],
                    [
                        -2.59988,
                        51.4506005,
                        0
                    ],
                    [
                        -2.5999832,
                        51.4501241,
                        0
                    ],
                    [
                        -2.6009005,
                        51.4498199,
                        0
                    ]
                ]
            },
            "properties": {
                "name": "walk-route"
            }
        }    
    ]
};
